spring:
  profiles:
    group:
      dev: "dev, datasource"
      prod: "prod, datasource"
    include:
      - security
      - infra
  servlet:
    multipart:
      max-file-size: 10MB
swagger:
  version: ${SWAGGER_VERSION:0.0.1}